spring.datasource.url=jdbc:mysql://localhost:3306/home_order_dev
spring.datasource.username=root
spring.datasource.password=home-order-password

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true